version: 1
disable_existing_loggers: False


filters:
  masking:
    (): core.logging_.filters.maskingfilter.MaskingFilter
    mask: "*****"
    patterns:
      - "AToken:[a-z0-9]+"
      - "(?<=(?:\"|')password(?:\"|'): (?:\"|'))[^\"']+(?=(?:\"|'))"
      - "(?<=(?:\"|')Authorization(?:\"|'): (?:\"|')Basic )[^\"']+(?=(?:\"|'))"
      - "(?<=(?:\"|')Auth(?:\"|'): \\()(.*)(?=\\), (?:\"|'))"
      - "(?<=(?:\"|')access_token(?:\"|'): (?:\"|'))[^\"']+(?=(?:\"|'))"

handlers:
  socket:
    (): core.logging_.handlers.jsonsockethandler.JSONSocketHandler
    filters:
      - masking
    host: log-receiver
    # host: 'localhost'
    port: 9021

root:
  handlers:
    - socket
  level: INFO