version: 1
disable_existing_loggers: False


filters:
  masking:
    (): core.logging_.filters.maskingfilter.MaskingFilter
    mask: "*****"
    patterns:
      - "AToken:[a-z0-9]+"
      - "(?<=(?:\"|')password(?:\"|'): (?:\"|'))[^\"']+(?=(?:\"|'))"
      - "(?<=(?:\"|')Authorization(?:\"|'): (?:\"|')Basic )[^\"']+(?=(?:\"|'))"
      - "(?<=(?:\"|')Auth(?:\"|'): \\()(.*)(?=\\), (?:\"|'))"
      - "(?<=(?:\"|')access_token(?:\"|'): (?:\"|'))[^\"']+(?=(?:\"|'))"
  appname:
    (): core.logging_.filters.namefilter.AppFilter
  requestid:
    (): main.RequestIdFilter

formatters:
  simple:
    format: '%(request_id)s - %(asctime)s - %(source)s - %(levelname)s - %(message)s'

handlers:
  socket:
    (): core.logging_.handlers.jsonsockethandler.JSONSocketHandler
    filters:
      - masking
      - appname
      - requestid
    formatter: simple
    host: log-receiver
    # host: 'localhost'
    port: 9021

root:
  handlers:
    - socket
  level: DEBUG